# Generated by Django 4.0.2 on 2022-02-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listmodel',
            name='Timestamp',
        ),
        migrations.AlterField(
            model_name='listmodel',
            name='Status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('WORKING', 'WORKING'), ('DONE', 'DONE'), ('OVERDUE', 'OVERDUE')], default='OPEN', max_length=7),
        ),
    ]
