# Generated by Django 4.0.2 on 2022-02-15 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0003_alter_listmodel_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Created at'),
            preserve_default=False,
        ),
    ]
